version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filmsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./FilmManagementSystem
    container_name: film_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - app_network
      
  frontend:
    tty: true
    build: 
      context: ./film-management-client
      dockerfile: Dockerfile
    container_name: film_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  postgres_data:
networks:
  app_network:
    driver: bridge